[phases.setup]
nixPkgs = ["python311", "poetry", "nodejs_20"]

[phases.install]
cmds = [
  "poetry install --no-interaction",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npm start"
